services:
  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    labels:
      - "traefik.enable=false"

  kibana:
    image: kibana:8.8.1
    container_name: kibana
    networks:
      - 'web'
    ports:
      - 127.0.0.1:5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: your_password
    depends_on:
      - elasticsearch
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.kibana.rule: "Host(`example.com`)"
      traefik.http.routers.kibana.tls.certresolver: "letsencrypt"
      traefik.http.routers.kibana.entrypoints: "http,https"
      traefik.http.services.kibana.loadbalancer.server.port: "5601"

volumes:
  esdata:
    driver: local

networks:
  web:
    external: true

# docker compose exec -it elasticsearch ./bin/elasticsearch-reset-password -u kibana_system
# docker compose exec -it elasticsearch ./bin/elasticsearch-reset-password -u elastic
