services:
  elasticsearch:
    image: elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=your_password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    labels:
      - "traefik.enable=false"

  kibana:
    image: kibana:7.13.4
    container_name: kibana
    networks:
      - 'web'
    ports:
      - 127.0.0.1:5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: your_password
    depends_on:
      - elasticsearch
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.kibana.rule: "Host(`example.com`)"
      traefik.http.routers.kibana.tls.certresolver: "letsencrypt"
      traefik.http.routers.kibana.entrypoints: "http,https"
      traefik.http.services.kibana.loadbalancer.server.port: "5601"

volumes:
  esdata:
    driver: local

networks:
  web:
    external: true
